baseURL = 'http://localhost'
languageCode = 'en-us'
title = 'myblog'
theme = "paperesque"

# Uncomment these lines for droplist / resource removal support! See the
# README for more details

# [outputs]
# page = ["HTML", "droplist"]

[params]
# Turn this on if you want to disable margin notes everywhere!
# disableMarginNotes = true

# Customise your home page menu here:

[[params.menu]]
  name = "Recent Posts"
  url = "posts/"

[[params.menu]]
  name = "Posts by Tag"
  url = "tags/"

[[params.menu]]
  name = "About the contents of this example"
  url = "about/"

[[params.menu]]
  name = "Hugo Themes default example pages"
  url = "tags/hugobasicsite/"

[[params.menu]]
  name = "Link to theme on Github"
  url = "https://github.com/capnfabs/paperesque"


# And your top-right menu links here.

[[params.topmenu]]
  name = "about"
  url = "about/"

[[params.topmenu]]
  name = "contact"
  url = "contact/"

[[params.topmenu]]
  name = "Lastet Project: Film.fyi"
  url = "https://film.fyi"

[[params.topmenu]]
  name = "rss"
  url = "posts/index.xml"


